# Generated by Django 4.2.7 on 2023-11-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_unit_price_from_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
