# Generated by Django 4.2.7 on 2023-11-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeditem',
            old_name='like',
            new_name='user',
        ),
    ]
